Allow external definition of CPM_DOWNLOAD_LOCATION
ClausKlein/netkit-tftp pull request #3
Opened 2023-02-10 12:45 UTC by slayerrensky

Allow external definition of CPM_DOWNLOAD_LOCATION

2023-02-10 21:32 UTC, ClausKlein requested changes

2023-02-10 21:32 UTC, ClausKlein commented on cmake/CPM.cmake
> -endfunction()
Das macht die letzten Änderungen wieder Rückgängig: see https://github.com/ClausKlein/CPM.cmake/commits/master/cmake/get_cpm.cmake

2023-02-10 21:32 UTC, ClausKlein commented on cmake/CPM.cmake
> +    file(READ ${CPM_DOWNLOAD_LOCATION} FILE_CONTENTS)
Warum, was soll das bewirken?

2023-02-13 08:23 UTC, slayerrensky commented on cmake/CPM.cmake
> -endfunction()
Ich schau nochmal drüber, es kann gut sein das ich einen älteren stand als Basis genommen habe.

2023-02-13 08:55 UTC, ClausKlein commented on cmake/CPM.cmake
> -endfunction()
Hier solltest du den PR stellen: https://github.com/cpm-cmake/CPM.cmake/pulls

Ich nutze immer dir last stable version!

2023-02-13 13:00 UTC, merged